/**
 * Session Cleanup Extension
 *
 * Deletes OLD, UNNAMED session files. It never touches a session that has a
 * display name (whether set manually via `/name` / `--name` / Ctrl+R or
 * auto-generated by pi) and never touches the currently active session.
 *
 * Deletion goes through the `trash` CLI first (recoverable) and only falls
 * back to a hard `unlink` if `trash` is not installed.
 *
 * Commands:
 *   /session-cleanup-now   -> delete old unnamed sessions
 *   /session-cleanup-dry   -> show what would be deleted
 *
 * Age threshold: PI_SESSION_CLEANUP_DAYS (positive integer, default 3).
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { SessionManager } from "@earendil-works/pi-coding-agent";
import { resolve } from "node:path";
import { existsSync } from "node:fs";
import { stat, unlink } from "node:fs/promises";
import { spawnSync } from "node:child_process";

const EXT_ID = "session-cleanup";
const DEFAULT_MAX_AGE_DAYS = 3;
const MS_PER_DAY = 24 * 60 * 60 * 1000;

/** Age in days. Reads the advertised PI_SESSION_CLEANUP_DAYS (was previously ignored). */
function getMaxAgeDays(): number {
  const raw = process.env.PI_SESSION_CLEANUP_DAYS;
  if (raw !== undefined && raw.trim() !== "") {
    const parsed = Number.parseInt(raw, 10);
    if (Number.isFinite(parsed) && parsed > 0) return parsed;
  }
  return DEFAULT_MAX_AGE_DAYS;
}

interface CleanupStats {
  deleted: number;
  kept: number; // recent (within cutoff), unnamed
  protected: number; // named and/or current session — never deleted
  candidates: number; // unnamed + old (what a real run would delete)
  errors: number;
  dryRun: boolean;
}

/**
 * A session is "protected" (never deleted) when it has a non-empty display
 * name. `SessionInfo.name` is already trimmed and normalized to `undefined`
 * when empty by SessionManager, so a truthy value means the user (or pi's
 * auto-title) gave it a name.
 */
function hasName(session: { name?: string }): boolean {
  return typeof session.name === "string" && session.name.trim().length > 0;
}

/**
 * Delete a session file, trying the `trash` CLI first (recoverable), then
 * falling back to a hard `unlink`. Mirrors pi's own session-picker behaviour.
 * Returns true when the file is gone.
 */
async function deleteSessionFile(path: string): Promise<boolean> {
  const trashArgs = path.startsWith("-") ? ["--", path] : [path];
  const result = spawnSync("trash", trashArgs, { encoding: "utf-8" });
  // `trash` not installed (error) or non-zero: fall through. If it reported
  // success or the file is gone, we are done.
  if (result.status === 0 || !existsSync(path)) return true;
  await unlink(path);
  return true;
}

async function cleanupSessions(
  dryRun: boolean,
  currentSessionPath: string | undefined,
): Promise<CleanupStats> {
  const maxAgeDays = getMaxAgeDays();
  const cutoff = Date.now() - maxAgeDays * MS_PER_DAY;
  const current = currentSessionPath ? resolve(currentSessionPath) : undefined;

  const sessions = await SessionManager.listAll();
  const stats: CleanupStats = {
    deleted: 0,
    kept: 0,
    protected: 0,
    candidates: 0,
    errors: 0,
    dryRun,
  };

  for (const session of sessions) {
    const path = resolve(session.path);
    try {
      // 1) Never delete the live session.
      if (current && path === current) {
        stats.protected++;
        continue;
      }
      // 2) Never delete a named session (manual or auto-titled).
      if (hasName(session)) {
        stats.protected++;
        continue;
      }
      // 3) Keep recent sessions.
      if (session.modified.getTime() >= cutoff) {
        stats.kept++;
        continue;
      }
      // 4) Old + unnamed -> candidate.
      stats.candidates++;
      if (!dryRun) {
        await stat(path); // ensure it still exists
        await deleteSessionFile(path);
        stats.deleted++;
      }
    } catch {
      stats.errors++;
    }
  }

  return stats;
}

export default function sessionCleanupExtension(pi: ExtensionAPI): void {
  pi.registerCommand("session-cleanup-now", {
    description:
      "Delete OLD UNNAMED session files (never named or the current session). Age via PI_SESSION_CLEANUP_DAYS (default 3).",
    handler: async (_args, ctx) => {
      const stats = await cleanupSessions(false, ctx.sessionManager.getSessionFile());
      ctx.ui.notify(
        `[${EXT_ID}] deleted ${stats.deleted} unnamed · kept ${stats.kept} recent · protected ${stats.protected} named/current · errors ${stats.errors} (older than ${getMaxAgeDays()}d)`,
        stats.errors ? "warning" : "info",
      );
    },
  });

  pi.registerCommand("session-cleanup-dry", {
    description:
      "Dry run: show how many OLD UNNAMED sessions would be deleted (named + current are always protected).",
    handler: async (_args, ctx) => {
      const stats = await cleanupSessions(true, ctx.sessionManager.getSessionFile());
      ctx.ui.notify(
        `[${EXT_ID}] dry-run: would delete ${stats.candidates} unnamed · protected ${stats.protected} named/current · kept ${stats.kept} recent · errors ${stats.errors} (older than ${getMaxAgeDays()}d)`,
        stats.errors ? "warning" : "info",
      );
    },
  });
}
